version: 2

models:
  - name: location
    description: "Dimensão geográfica"
    columns:
      - name: city_id
        description: "Chave primária da tabela"
        tests:
          - unique
          - not_null
      - name: state_id
        description: "Código do estado"
        tests:
          - not_null
      - name: country_id
        description: "Código do pais"
        tests:
          - not_null
  
  - name: account_customers
    description: "Tabela de conta do cliente"
    columns:
      - name: account_id
        description: "Chave primária da tabela"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Código do cliente"
        tests:
          - unique
          - not_null
      - name: city_id
        description: "Código da cidade"
        tests:
          - not_null
          - relationships:
              to: ref('location')
              field: city_id
      - name: account_status
        description: "Situação da conta"
        tests:
          - not_null
          - accepted_values:
              values: ['active', 'inactive']
      - name: customer_cpf
        description: "CPF do cliente"
        tests:
          - unique
          - not_null

  - name: financial_movements
    description: "Tabela de registro das movimentação financeiras"
    columns:
      - name: movement_id
        description: "Chave primária da tabela"
        tests:
          - unique
          - not_null
      - name: account_id
        description: "Código da conta"
        tests:
          - not_null
          - relationships:
              to: ref('account_customers')
              field: account_id
      - name: movement_requested_at
        description: "Data da movimentação na conta"
        tests:
          - not_null
          - relationships:
              to: ref('d_time')
              field: time_id
      - name: movement_completed_at
        description: "Data da conclusão da movimentação"
        tests:
          - relationships:
              to: ref('d_time')
              field: time_id
      - name: movement_status
        description: "Situação/Status da movimentação"
        tests:
          - not_null
          - accepted_values:
              values: ['completed', 'failed']
      - name: movement_in_or_out
        description: "Registro se a movimentação foi interna ou externa"
        tests:
          - not_null
          - accepted_values:
              values: ['in', 'out']
      - name: movement_type
        description: "Tipo da movimentação"
        tests:
          - accepted_values:
              values: ['pix', 'transfer']
  
  - name: d_time
    columns:
      - name: time_id
        description: "Chave primária da tabela"
        tests:
          - unique
          - not_null
      - name: action_timestamp
        description: ""
        tests:
          - unique
          - not_null